### ISSUE TITLE
Error downloading S6E15

### ISSUE THREAD

**Issue by jason-jxc** [xypwn/southpark-downloader-ui#25] opened 2024-12-04 22:44 UTC
Version: 0.0.1 build 229
Error: GetEpisodeStream: invalid master URL: does not point to master.m3u8
OS: windows amd64
Region: DE
Description: Error downloading S6E15

- [x] I understand that this issue will be deleted if I forget to fill out any of the fields surrounded by brackets ("[ ]"), including the title. Place an "x" into the brackets at the beginning of this line to confirm.

(Created via app)

**Comment by xypwn** [comment] 2024-12-18 11:54
Duplicate of #23

**Closed by xypwn** 2024-12-18 11:54 UTC
