### ISSUE TITLE
Internal Error Bug Report [Automatically Created via App]

### ISSUE THREAD

**Issue by Zandiexoder** [xypwn/southpark-downloader-ui#11] opened 2024-04-12 08:39 UTC
Version: 0.0.1 build 1
Error: GetEpisodeVTTSubtitles: get 'https://vs-tools.mtvnservices.com/caption/convert?mgid=mgid:file:gsp:alias:/mediabus/DTC/southParkStudiosUSen/359745/HDSS1204P2/HDSS1204P2_en-US_v2.dfxp.xml&accountName=intl.mtvi.com': HTTP error: 404 Not Found 
this error was shown for all S12 episodes

**Comment by xypwn** [comment] 2024-05-08 15:45
Duplicate of #10

**Closed by xypwn** 2024-05-08 15:45 UTC
