### ISSUE TITLE
Wrong URL redirection for US region

### ISSUE THREAD

**Issue by verdverm** [xypwn/southpark-downloader-ui#4] opened 2023-09-18 16:48 UTC
```
retrieve series MGID in website data JSON: unable to find JSON data in webpage
```

**Comment by xypwn** [comment] 2023-09-19 08:43
Hi,
thanks for reporting. Could you please specify which episode you're downloading and which OS you're on?
Also, make sure you're using the most recent version.
I'm not home right now, so I can't check for reproducibility yet, but it'd be great if you could do those things in the meantime :)

**Comment by verdverm** [comment] 2023-09-19 09:45
It was on startup, probably while fetching the catalog?

I'm on debian, cloned and built the latest myself

**Comment by xypwn** [comment] 2023-09-19 09:50
Yes, it definitely was trying to fetch the catalog. Strange that it didn't work though, since I just tried on my Android phone and it worked OK (an older version supports Android).

It could be something to do with your region. Which country does the web service think you're in?
Also, what happens when you try playing from https://www.southparkstudios.com?

**Comment by verdverm** [comment] 2023-09-19 09:52
I'm in the US, when I go to that link, I get redirected to https://southpark.cc.com/ which looks to be working fine

**Comment by verdverm** [comment] 2023-09-19 09:53
Are there any URLs that would be helpful for me to print? I can modify the code

**Comment by verdverm** [comment] 2023-09-19 09:57
```
$ southpark-downloader-ui 
STORAGE: Saving config
any: https://www.southpark.cc.com/seasons/south-park/yjy8n9/season-1
base: https://www.southpark.cc.com
```

![image](https://github.com/xypwn/southpark-downloader-ui/assets/1390600/395f6411-db60-4b87-87b8-418cea08cf9a)

**Comment by xypwn** [comment] 2023-09-19 10:03
Ohh. I know the problem now. Since it starts from www.southparkstudios.com it tries to redirect to www.southpark.cc.com, but only the non-www version seems to work in this case. I'll fix it and upload once I get home. In the meantime you can just remove the www. in the code and it should also work for you.

**Comment by xypwn** [comment] 2023-09-19 10:04
Nice work debugging this so quickly!

**Comment by verdverm** [comment] 2023-09-19 10:15
Go this error once, but it seems to go away?

![image](https://github.com/xypwn/southpark-downloader-ui/assets/1390600/cb57904f-b164-4141-a0bf-22843b68a48a)

Every episode appears to be Unavailable

![image](https://github.com/xypwn/southpark-downloader-ui/assets/1390600/eb63c283-5bc6-4320-8d3e-b02d40a9e775)

**Comment by xypwn** [comment] 2023-09-19 23:20
Cool! I actually made this project to learn about fyne as well as programming video downloaders.

I think fyne can be really great for making GUIs without having to put in a lot of effort. It aims to be pretty simple to use, just like go itself, although in my opinion it does still have quite a few footguns. For example the widget callbacks aren't thread-safe for accessing the widget data, meaning you have to implement locking yourself. Also there are still some bugs and missing features (e.g. I just made a PR for undo/redo, which it doesn't have at the moment). In general though, I can definitely recommend it. It's easy to get started and the [discord server](https://discord.gg/vvBuDfD5gP) has been a great resource for asking for help.

The 500 must be caused by SP an server bug. It happens sometimes, but is completely unpredictable from what I can tell. Maybe in the future I'll implement an auto-retry on 500. I think that's what the website does and why they probably didn't even fix the internal bug.

**Comment by xypwn** [comment] 2023-09-20 19:15
I just committed the change :)

**Closed by xypwn** 2023-09-20 19:15 UTC
